package ui.dashboard;

import auth.Session;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hui Nan
 */

public class PayrollDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PayrollDashboard
     */
    
    public PayrollDashboard() {
        initComponents();
        String username = Session.getUsername();
        String role = Session.getRole();
        
        empName.setText(username);
        empRole.setText(role);
        
        if (Session.isLoggedIn()) {
            String userId = Session.getUserId();
        } else {
            System.out.println("User is not logged in.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        updateText = new javax.swing.JLabel();
        updatePicture = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        recordText = new javax.swing.JLabel();
        recordPicture = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        payslipText = new javax.swing.JLabel();
        payslipPicture = new javax.swing.JLabel();
        Payslip = new javax.swing.JButton();
        createText = new javax.swing.JLabel();
        createPicture = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        empRole = new javax.swing.JLabel();
        btnLeave = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        empName = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnAnnouncements = new javax.swing.JButton();
        createPicture1 = new javax.swing.JLabel();
        createPicture2 = new javax.swing.JLabel();
        btnProfile2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setToolTipText("");
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(128, 128, 128));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        header.setText("HUMAN RESOURCE MANAGEMENT SYSTEM");
        header.setToolTipText("");
        headerPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 535, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 810, 50));

        title.setFont(new java.awt.Font("Sitka Text", 2, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Payroll Management");
        mainPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 740, 50));

        updateText.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        updateText.setText("Update");
        mainPanel.add(updateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, 30));

        updatePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/Update.png"))); // NOI18N
        mainPanel.add(updatePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 240, 170));

        update.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        mainPanel.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 240, 210));

        recordText.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        recordText.setText("Record");
        mainPanel.add(recordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, 20));

        recordPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/Record.png"))); // NOI18N
        mainPanel.add(recordPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 240, 170));

        search.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        mainPanel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 240, 210));

        payslipText.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        payslipText.setText("Payslip");
        mainPanel.add(payslipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, -1, 30));

        payslipPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/Payslip.png"))); // NOI18N
        mainPanel.add(payslipPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 240, 170));

        Payslip.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayslipActionPerformed(evt);
            }
        });
        mainPanel.add(Payslip, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 240, 210));

        createText.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        createText.setText("Create");
        mainPanel.add(createText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        createPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/Create.png"))); // NOI18N
        mainPanel.add(createPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, 190));

        create.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        create.setToolTipText("");
        create.setAutoscrolls(true);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        mainPanel.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 240, 210));

        sidePanel.setBackground(new java.awt.Color(128, 128, 128));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empRole.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        empRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empRole.setText("Payroll Officer");
        sidePanel.add(empRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, -1));

        btnLeave.setText("Leave");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });
        sidePanel.add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, 50));

        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        sidePanel.add(btnAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 130, 50));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        sidePanel.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 130, 50));

        empName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        empName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empName.setText("EmpName");
        empName.setToolTipText("");
        sidePanel.add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, -1));

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/PayrollProfile.png"))); // NOI18N
        sidePanel.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 160, 200));

        btnProfile.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnProfile.setText("View Profile");
        btnProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        sidePanel.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        btnHistory.setText("History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        sidePanel.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 130, 50));

        btnAnnouncements.setText("Announcements");
        btnAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnouncementsActionPerformed(evt);
            }
        });
        sidePanel.add(btnAnnouncements, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 130, 50));

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        createPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/Create.png"))); // NOI18N
        mainPanel.add(createPicture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, 190));

        createPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/Create.png"))); // NOI18N
        mainPanel.add(createPicture2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, 190));

        btnProfile2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnProfile2.setText("View Profile");
        btnProfile2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfile2ActionPerformed(evt);
            }
        });
        mainPanel.add(btnProfile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        payrollManagement.payrollManager.Update.Update update = new payrollManagement.payrollManager.Update.Update();
        update.setVisible(true);
        dispose();
    }//GEN-LAST:event_updateActionPerformed

    private void PayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayslipActionPerformed
        payrollManagement.payrollManager.Payslip.SearchPayslip searchPayslip = new payrollManagement.payrollManager.Payslip.SearchPayslip();
        searchPayslip.setVisible(true);
        dispose();
    }//GEN-LAST:event_PayslipActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        payrollManagement.payrollManager.Record.Record record = new payrollManagement.payrollManager.Record.Record();
        record.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        attendanceManagement.Attendance attendance = new attendanceManagement.Attendance();
        attendance.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        auth.Session.logout();
        JOptionPane.showMessageDialog(this, "You have been logged out.");
        this.dispose();
        System.exit(0);        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        payrollManagement.payrollManager.Create.Create create = new payrollManagement.payrollManager.Create.Create();
        create.setVisible(true);
        dispose();
    }//GEN-LAST:event_createActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        String filePath = "usertxt.txt";
        File file = new File(filePath);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            String userId = auth.Session.getUserId(); 

            while ((line = br.readLine()) != null) {
                String[] dataRow = line.split(",");

                if (dataRow[0].equals(userId)) {
                    String userID = dataRow[0];
                    String username = dataRow[1];
                    String password = dataRow[2];
                    String fullName = dataRow[3];
                    String gender = dataRow[4];
                    String dateOfBirth = dataRow[5];
                    String phoneNumber = dataRow[6];
                    String maritalStatus = dataRow[7];
                    String nationality = dataRow[8];
                    String email = dataRow[9];
                    String address = dataRow[10];
                    String role = dataRow[11];
                    String position = dataRow[12];
                    String department = dataRow[13];
                    String datejoined = dataRow[14];
                    String employmentType = dataRow[15];
                    String workTitle = dataRow[16];
                    String workResponsibilities = dataRow[17];
                    String emergencyName = dataRow[18];
                    String emergencyPhoneNo = dataRow[19];
                    String bankName = dataRow[20];
                    String accountNumber = dataRow[21];
                    
                    
                    profile.ViewProfile viewprofile = new profile.ViewProfile();              
                    viewprofile.setLabelValues(userID, username, password,fullName, gender, dateOfBirth,
                           phoneNumber, maritalStatus, nationality, email, address,
                           role, position, department, datejoined, employmentType,
                           workTitle, workResponsibilities, emergencyName, emergencyPhoneNo,
                           bankName, accountNumber);
                    viewprofile.setVisible(true);
                    this.dispose();
                }
            }
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(profile.ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnProfile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfile2ActionPerformed

    private void btnAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnouncementsActionPerformed
        adminManagement.DisplayA.DisplayAnnoucement diplayAnnoucement = new adminManagement.DisplayA.DisplayAnnoucement();
        diplayAnnoucement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnnouncementsActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        payrollManagement.payrollManager.History.History history = new payrollManagement.payrollManager.History.History();
        history.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PayrollDashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Payslip;
    private javax.swing.JLabel Profile;
    private javax.swing.JButton btnAnnouncements;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnProfile2;
    private javax.swing.JButton create;
    private javax.swing.JLabel createPicture;
    private javax.swing.JLabel createPicture1;
    private javax.swing.JLabel createPicture2;
    private javax.swing.JLabel createText;
    private javax.swing.JLabel empName;
    private javax.swing.JLabel empRole;
    private javax.swing.JLabel header;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel payslipPicture;
    private javax.swing.JLabel payslipText;
    private javax.swing.JLabel recordPicture;
    private javax.swing.JLabel recordText;
    private javax.swing.JButton search;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JLabel updatePicture;
    private javax.swing.JLabel updateText;
    // End of variables declaration//GEN-END:variables
}