package payrollManagement.payrollManager.Create;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hui Nan
 */

public class Create extends javax.swing.JFrame {

    /**
     * Creates new form Create
     */
       
    public Create() {
        initComponents();
    }

    public void setButtonValues(String empID, String empName, String department, String employmenttype, String dateOfJoined, String bankname, String bankaccount) {
        lEmpID.setText(empID);
        lEmpName.setText(empName);
        lDep.setText(department);
        lEmpType.setText(employmenttype);
        lDOJ.setText(dateOfJoined);
        lBankName.setText(bankname);
        lBankAccount.setText(bankaccount);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        header1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        btnAddEmp = new javax.swing.JButton();
        btnCal = new javax.swing.JButton();
        box = new javax.swing.JPanel();
        empID = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        empName = new javax.swing.JLabel();
        doj = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        BasicSalary = new javax.swing.JLabel();
        btnBasicSalary = new javax.swing.JTextField();
        btnMonth = new javax.swing.JComboBox<>();
        btnViewEmp = new javax.swing.JButton();
        BankName = new javax.swing.JLabel();
        BankAccount = new javax.swing.JLabel();
        dep1 = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        btnYear = new javax.swing.JTextField();
        lEmpID = new java.awt.Label();
        lBankName = new java.awt.Label();
        lBankAccount = new java.awt.Label();
        lDOJ = new java.awt.Label();
        lEmpType = new java.awt.Label();
        lDep = new java.awt.Label();
        lEmpName = new java.awt.Label();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        EmpTab = new javax.swing.JTabbedPane();
        box1 = new javax.swing.JPanel();
        allowance = new javax.swing.JLabel();
        btnAllowance = new javax.swing.JTextField();
        btnLatePen = new javax.swing.JTextField();
        latePen = new javax.swing.JLabel();
        OT = new javax.swing.JLabel();
        btnOT = new javax.swing.JTextField();
        GSalary = new javax.swing.JLabel();
        btnGSalary = new javax.swing.JTextField();
        yeeEPF = new javax.swing.JLabel();
        yeeSosco = new javax.swing.JLabel();
        yeeEIS = new javax.swing.JLabel();
        yeePCB = new javax.swing.JLabel();
        yeeTDeduction = new javax.swing.JLabel();
        btnYeePCB = new javax.swing.JTextField();
        btnYeeSosco = new javax.swing.JTextField();
        btnYeeEPF = new javax.swing.JTextField();
        salaryDeduction = new javax.swing.JLabel();
        salaryEarning = new javax.swing.JLabel();
        YeeAmount = new javax.swing.JLabel();
        btnYeeEIS = new javax.swing.JTextField();
        btnYeeNetSalary = new javax.swing.JTextField();
        yeeNetSalary = new javax.swing.JLabel();
        btnYeeTDeduction = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        yerEPF = new javax.swing.JLabel();
        yerSosco = new javax.swing.JLabel();
        yerEIS = new javax.swing.JLabel();
        btnYerEPF = new javax.swing.JTextField();
        btnYerSosco = new javax.swing.JTextField();
        btnYerEIS = new javax.swing.JTextField();
        YerAmount = new javax.swing.JLabel();
        yerCon = new javax.swing.JLabel();
        btnYerCon = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));
        mainPanel.setToolTipText("");
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel1.setToolTipText("");
        mainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(128, 128, 128));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header1.setText("EMPLOYEE DETAILS");
        header1.setToolTipText("");
        header.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 535, -1));

        mainPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        mainPanel.add(mainPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        title1.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 0, 0));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title1.setText("Employee Payroll Details");
        mainPanel.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 280, 50));

        btnAddEmp.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAddEmp.setText("Add Details");
        btnAddEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        mainPanel.add(btnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 110, 30));

        btnCal.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnCal.setText("Calculate");
        btnCal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        mainPanel.add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 110, 30));

        box.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));
        box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        empID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empID.setText("Employee ID             :");

        dep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dep.setText("Department              :");

        empName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empName.setText("Employee Name       :");

        doj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doj.setText("Date of Joining        :");

        month.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        month.setText("Month                       :");

        BasicSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BasicSalary.setText("Basic Salary              :");

        btnBasicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasicSalaryActionPerformed(evt);
            }
        });

        btnMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        btnMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthActionPerformed(evt);
            }
        });

        btnViewEmp.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnViewEmp.setText("View Employee");
        btnViewEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmpActionPerformed(evt);
            }
        });

        BankName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BankName.setText("Bank Name              :");

        BankAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BankAccount.setText("Bank Account          :");

        dep1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dep1.setText("Employment Type    :");

        Year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Year.setText("Year                           :");

        btnYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxLayout = new javax.swing.GroupLayout(box);
        box.setLayout(boxLayout);
        boxLayout.setHorizontalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnViewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(boxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxLayout.createSequentialGroup()
                            .addComponent(dep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lEmpType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxLayout.createSequentialGroup()
                            .addComponent(empName)
                            .addGap(30, 30, 30)
                            .addComponent(lEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(boxLayout.createSequentialGroup()
                            .addComponent(dep)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lDep, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(BasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BankName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(month)
                        .addGroup(boxLayout.createSequentialGroup()
                            .addComponent(doj)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lDOJ, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(boxLayout.createSequentialGroup()
                            .addComponent(empID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBasicSalary, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lBankName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addGroup(boxLayout.createSequentialGroup()
                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnMonth, javax.swing.GroupLayout.Alignment.TRAILING, 0, 199, Short.MAX_VALUE)
                                .addComponent(btnYear, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        boxLayout.setVerticalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empID)
                    .addComponent(lEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empName)
                    .addComponent(lEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(boxLayout.createSequentialGroup()
                        .addComponent(dep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boxLayout.createSequentialGroup()
                                .addComponent(dep1)
                                .addGap(18, 18, 18)
                                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(boxLayout.createSequentialGroup()
                                        .addComponent(doj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Year)
                                            .addComponent(btnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(month))
                                        .addGap(18, 18, 18)
                                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(BasicSalary)
                                            .addComponent(btnBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BankName)
                                            .addComponent(lBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BankAccount)
                                            .addComponent(lBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lDOJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lEmpType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnViewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        mainPanel.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 430, 450));
        mainPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        EmpTab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        allowance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allowance.setText("Allowance                 :");

        btnAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowanceActionPerformed(evt);
            }
        });

        btnLatePen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatePenActionPerformed(evt);
            }
        });

        latePen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        latePen.setText("Late Penalty              :");

        OT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OT.setText("Over Time                 :");

        btnOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOTActionPerformed(evt);
            }
        });

        GSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GSalary.setForeground(new java.awt.Color(0, 51, 255));
        GSalary.setText("Gross Salary              :");

        btnGSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGSalaryActionPerformed(evt);
            }
        });

        yeeEPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeEPF.setText("EPF                            :");

        yeeSosco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeSosco.setText("Sosco                        :");

        yeeEIS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeEIS.setText("EIS                             :");

        yeePCB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeePCB.setText("PCB                           :");

        yeeTDeduction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeTDeduction.setForeground(new java.awt.Color(0, 51, 255));
        yeeTDeduction.setText("Total Deduction       :");

        btnYeePCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeePCBActionPerformed(evt);
            }
        });

        btnYeeSosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeeSoscoActionPerformed(evt);
            }
        });

        btnYeeEPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeeEPFActionPerformed(evt);
            }
        });

        salaryDeduction.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        salaryDeduction.setForeground(new java.awt.Color(255, 0, 0));
        salaryDeduction.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salaryDeduction.setText("Salary Deduction");

        salaryEarning.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        salaryEarning.setForeground(new java.awt.Color(255, 0, 0));
        salaryEarning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salaryEarning.setText("Salary Earning");

        YeeAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        YeeAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YeeAmount.setText("Amount (RM)");

        btnYeeEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeeEISActionPerformed(evt);
            }
        });

        btnYeeNetSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeeNetSalaryActionPerformed(evt);
            }
        });

        yeeNetSalary.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        yeeNetSalary.setForeground(new java.awt.Color(255, 0, 0));
        yeeNetSalary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        yeeNetSalary.setText("Net Salary                :");

        btnYeeTDeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeeTDeductionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout box1Layout = new javax.swing.GroupLayout(box1);
        box1.setLayout(box1Layout);
        box1Layout.setHorizontalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(box1Layout.createSequentialGroup()
                        .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(box1Layout.createSequentialGroup()
                                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(allowance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(latePen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(box1Layout.createSequentialGroup()
                                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salaryDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yeeEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yeeSosco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yeeEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yeePCB)
                                    .addComponent(yeeNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yeeTDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(salaryEarning, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)))
                        .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLatePen, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(btnAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnYeeSosco)
                            .addComponent(btnYeeEPF)
                            .addComponent(btnGSalary)
                            .addComponent(btnYeeEIS)
                            .addComponent(btnYeePCB)
                            .addComponent(btnYeeTDeduction)
                            .addComponent(btnYeeNetSalary)))
                    .addComponent(YeeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1075, 1075, 1075))
        );
        box1Layout.setVerticalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YeeAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salaryEarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allowance)
                    .addComponent(btnAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOT)
                    .addComponent(OT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLatePen)
                    .addComponent(latePen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GSalary)
                    .addComponent(btnGSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeeEPF)
                    .addComponent(btnYeeEPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeeSosco)
                    .addComponent(btnYeeSosco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yeeEIS)
                    .addGroup(box1Layout.createSequentialGroup()
                        .addComponent(btnYeeEIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnYeePCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeePCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnYeeTDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeeTDeduction))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnYeeNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeeNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(228, 228, 228))
        );

        EmpTab.addTab("Employee", box1);

        yerEPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yerEPF.setText("EPF                                 :");

        yerSosco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yerSosco.setText("Sosco                             :");

        yerEIS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yerEIS.setText("EIS                                  :");

        btnYerEPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYerEPFActionPerformed(evt);
            }
        });

        btnYerSosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYerSoscoActionPerformed(evt);
            }
        });

        btnYerEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYerEISActionPerformed(evt);
            }
        });

        YerAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        YerAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YerAmount.setText("Amount (RM)");

        yerCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yerCon.setForeground(new java.awt.Color(0, 51, 255));
        yerCon.setText("Total Contribution        :");

        btnYerCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYerConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(YerAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(yerCon)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(yerEPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yerEIS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(yerSosco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnYerSosco, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(btnYerEPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnYerCon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnYerEIS))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(YerAmount)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnYerEPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(yerEPF)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yerSosco)
                            .addComponent(btnYerSosco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yerEIS)
                            .addComponent(btnYerEIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yerCon)
                    .addComponent(btnYerCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        EmpTab.addTab("Employer", jPanel2);

        mainPanel.add(EmpTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 430, 450));

        title.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        title.setForeground(new java.awt.Color(255, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("Employee Details");
        mainPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 50));

        btnReset.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        mainPanel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, -1, 30));

        btnExit.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        mainPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, -1, 30));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ui.dashboard.BackButton backButton = new ui.dashboard.BackButton();
        backButton.navigateBasedOnRole();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmpActionPerformed
        payrollManagement.payrollManager.Create.SearchUser search = new payrollManagement.payrollManager.Create.SearchUser();
        search.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewEmpActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        String empID = lEmpID.getText(); 
        String empName = lEmpName.getText();
        String year = btnYear.getText();
        String month = (String) btnMonth.getSelectedItem();
        String basicSalary = btnBasicSalary.getText();
        String allowance = btnAllowance.getText();
        String overtime = btnOT.getText();
        String latePen = btnLatePen.getText();
        String grossSalary = btnGSalary.getText();
        String yeeEPF = btnYeeEPF.getText();
        String yeeSosco = btnYeeSosco.getText();
        String yeeEIS = btnYeeEIS.getText();
        String yeePCB = btnYeePCB.getText();
        String yeeTDeduction = btnYeeTDeduction.getText();
        String yeeNetSalary = btnYeeNetSalary.getText();
        String yerEPF = btnYerEPF.getText(); 
        String yerSosco = btnYerSosco.getText();
        String yerEIS = btnYerEIS.getText();
        String yerCon = btnYerCon.getText();
        String BankName = lBankName.getText();
        String BankAccount = lBankAccount.getText();

        if (empID.isEmpty()|| empName.isEmpty()|| year.isEmpty()|| month.isEmpty()|| basicSalary.isEmpty()|| allowance.isEmpty() || 
            grossSalary.isEmpty() || yeeNetSalary.isEmpty() || yerEPF.isEmpty() || yerSosco.isEmpty() || yerEIS.isEmpty() || 
            yerCon.isEmpty() || BankName.isEmpty() || BankAccount.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String payrollID = String.valueOf(PayrollId.getNextPayrollId()); 

            String csvLine = String.format("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s",
                payrollID, empID, empName, year, month, basicSalary, allowance, overtime, 
                latePen, grossSalary, yeeEPF, yeeSosco, yeeEIS, yeePCB, yeeTDeduction, 
                yeeNetSalary, yerEPF, yerSosco, yerEIS, yerCon, BankName, BankAccount);

            try (BufferedWriter writer = new BufferedWriter(new FileWriter("payroll.txt", true))) {
                writer.write(csvLine);
                writer.newLine(); 
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error saving to file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Employee payroll details added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            lEmpID.setText("");
            lEmpName.setText("");
            lDep.setText("");
            lEmpType.setText("");
            lDOJ.setText("");
            lEmpName.setText("");
            btnYear.setText("");
            btnMonth.setSelectedIndex(0); 
            btnBasicSalary.setText("");
            btnAllowance.setText("");
            btnOT.setText("");
            btnLatePen.setText("");
            btnGSalary.setText("");
            btnYeeEPF.setText("");
            btnYeeSosco.setText("");
            btnYeeEIS.setText("");
            btnYeePCB.setText("");
            btnYeeTDeduction.setText("");
            btnYeeNetSalary.setText("");
            btnYerEPF.setText("");
            btnYerSosco.setText("");
            btnYerEIS.setText("");
            btnYerCon.setText("");
            lBankName.setText("");
            lBankAccount.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for salary-related fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddEmpActionPerformed
        
    private void btnMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMonthActionPerformed

    private void btnBasicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasicSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBasicSalaryActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        try {
            String month = (String) btnMonth.getSelectedItem();
            String year = btnYear.getText();
            String selectedUserId = lEmpID.getText(); 

            if (month == null || month.isEmpty()) {
                throw new IllegalArgumentException("Please select a valid month.");
            }
            if (year == null || year.isEmpty()) {
                throw new IllegalArgumentException("Please select a valid year.");
            }

            if (recordExistsForMonthAndYear(month, year, selectedUserId)) {
                JOptionPane.showMessageDialog(this, "A record for " + month + " " + year + " already exists for User ID " + selectedUserId + ".", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!attendanceExistsForMonthAndYear(month, year, selectedUserId)) {
                throw new IllegalArgumentException("No attendance records found for User ID " + selectedUserId + " in " + month + " " + year + ".");
            }

            String empType = lEmpType.getText();
            AttCalculation calculation = new AttCalculation();
            double basicSalary;
            double allowance = 100;

            switch (empType.toLowerCase()) {
                case "intern":
                    double totalDays = calculation.calculateInternSalary(selectedUserId);  
                    basicSalary = (1000 / 30) * totalDays;
                    break;
                case "full time":
                    basicSalary = 5000;
                    break;
                default:
                    throw new IllegalArgumentException("Please choose a valid employee type.");
            }

            btnBasicSalary.setText(String.format("%.2f", basicSalary));
            btnAllowance.setText(String.format("%.2f", allowance));

            String overtimeStr = calculation.calculateMonthlyOvertime(selectedUserId);
            if (overtimeStr == null || overtimeStr.isEmpty()) {
                overtimeStr = "00:00";  
            }

            LocalTime totalOvertime = LocalTime.parse(overtimeStr);
            double tOvertime = totalOvertime.getHour() + totalOvertime.getMinute() / 60.0;
            double overtimeAmount = tOvertime * 100;
            btnOT.setText(String.format("%.2f", overtimeAmount));

            String monthYear = month + "-" + year;
            int totalLateDays = calculation.calculateMonthlyUndertime(filePath, monthYear, selectedUserId);
            double deduction = 0.00;

            if (totalLateDays >= 3) {
                deduction = 100.0;
            }

            btnLatePen.setText(String.format("%.2f", deduction));

            double grossSalary = basicSalary + allowance + overtimeAmount - deduction;
            btnGSalary.setText(String.format("%.2f", grossSalary));

            double yeeEPF = grossSalary * 0.11;
            double yeeSOCSO = grossSalary * 0.005;
            double yeeEIS = grossSalary * 0.002;
            double yeePCB = (grossSalary * 12) * 0.05 / 12;

            btnYeeEPF.setText(String.format("%.2f", yeeEPF));
            btnYeeSosco.setText(String.format("%.2f", yeeSOCSO));
            btnYeeEIS.setText(String.format("%.2f", yeeEIS));
            btnYeePCB.setText(String.format("%.2f", yeePCB));

            double totalDeduction = yeeEPF + yeeSOCSO + yeeEIS + yeePCB;
            btnYeeTDeduction.setText(String.format("%.2f", totalDeduction));

            double netSalary = grossSalary - totalDeduction;
            btnYeeNetSalary.setText(String.format("%.2f", netSalary));

            double yerEPF = grossSalary * 0.13;
            double yerSOCSO = grossSalary * 0.018;
            double yerEIS = grossSalary * 0.002;

            btnYerEPF.setText(String.format("%.2f", yerEPF));
            btnYerSosco.setText(String.format("%.2f", yerSOCSO));
            btnYerEIS.setText(String.format("%.2f", yerEIS));

            double yerCon = yerEPF + yerSOCSO + yerEIS;
            btnYerCon.setText(String.format("%.2f", yerCon));

            generateSummary(selectedUserId, totalLateDays);  

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error in number formatting. Please check your inputs.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Error parsing time data. Please check the attendance file.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalActionPerformed
    
    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("HH:mm");
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String filePath = "attendance.txt";
 
    public int calculateMonthlyUndertime(String filePath, String monthYear, String selectedEmpID) throws IOException {
        int totalLateDays = 0;

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            reader.readLine();
            while ((line = reader.readLine()) != null) {
                String[] entry = line.split(",");
                if (entry.length < 8) {
                    System.err.println("Invalid line format: " + line);
                    continue;
                }

                String currentUserId = entry[1].trim();
                String dateStr = entry[7].trim();
                String undertimeStr = entry[6].trim();

                System.out.println("Processing: UserID=" + currentUserId + ", Date=" + dateStr + ", Undertime=" + undertimeStr);

                if (currentUserId.equals(selectedEmpID)) {
                    try {
                        LocalDate date = LocalDate.parse(dateStr, DATE_FORMAT);
                        String monthYearStr = date.getYear() + "-" + String.format("%02d", date.getMonthValue());

                        System.out.println("MonthYearStr=" + monthYearStr + ", ExpectedMonthYear=" + monthYear);

                        if (monthYearStr.equals(monthYear)) {
                            if (!"00:00".equals(undertimeStr)) { 
                                totalLateDays++;
                                System.out.println("Late day found: " + dateStr + " with undertime " + undertimeStr);
                            }
                        }
                    } catch (DateTimeParseException e) {
                        System.err.println("Date or time format error in line: " + line + " - " + e.getMessage());
                    }
                }
            }
        }
        System.out.println("Total late days: " + totalLateDays);
        return totalLateDays;
    }
    
    private boolean recordExistsForMonthAndYear(String month, String year, String lEmpID) throws IOException {
        Set<String> existingRecords = new HashSet<>();

        try (BufferedReader br = new BufferedReader(new FileReader("payroll.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 5) {  
                    String recordEmpID = parts[1].trim();  
                    String recordYear = parts[3].trim(); 
                    String recordMonth = parts[4].trim();  

                    if (recordEmpID.equalsIgnoreCase(lEmpID) && recordMonth.equalsIgnoreCase(month) && recordYear.equalsIgnoreCase(year)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    private static final Map<String, String> monthNameToNumber = new HashMap<>();

    static {
        monthNameToNumber.put("January", "01");
        monthNameToNumber.put("February", "02");
        monthNameToNumber.put("March", "03");
        monthNameToNumber.put("April", "04");
        monthNameToNumber.put("May", "05");
        monthNameToNumber.put("June", "06");
        monthNameToNumber.put("July", "07");
        monthNameToNumber.put("August", "08");
        monthNameToNumber.put("September", "09");
        monthNameToNumber.put("October", "10");
        monthNameToNumber.put("November", "11");
        monthNameToNumber.put("December", "12");
    }

    public boolean attendanceExistsForMonthAndYear(String monthName, String year, String selectedUserId) throws IOException {
        String month = monthNameToNumber.get(monthName);  
        DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        try (BufferedReader br = new BufferedReader(new FileReader("attendance.txt"))) {
            String line;

            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 8) {
                    String userId = parts[1].trim();  
                    String dateStr = parts[7].trim();

                    try {
                        LocalDate date = LocalDate.parse(dateStr, DATE_FORMAT); 
                        String recordYear = String.valueOf(date.getYear());
                        String recordMonth = String.format("%02d", date.getMonthValue());

                        if (userId.equals(selectedUserId) && recordMonth.equals(month) && recordYear.equals(year)) {
                            System.out.println("Record found: User " + userId + " for " + recordMonth + "/" + recordYear);  // Debugging
                            return true;
                        }
                    } catch (DateTimeParseException e) {
                        System.err.println("Date format error in line: " + line + " - " + e.getMessage());
                    }
                } else {
                    System.out.println("Skipping invalid line: " + line); 
                }
            }
        }
        return false; 
    }
    
    private double convertToDecimalHours(String overtimeStr) {
        if (overtimeStr == null || overtimeStr.isEmpty()) {
            return 0.0;
        }
        try {
            LocalTime totalOvertime = LocalTime.parse(overtimeStr, TIME_FORMAT);
            return totalOvertime.getHour() + totalOvertime.getMinute() / 60.0;
        } catch (DateTimeParseException e) {
            System.err.println("Error parsing overtime time data: " + e.getMessage());
            return 0.0;
        }
    }
    
    public void generateSummary(String lEmpID, int totalLateDays) throws IOException {
        AttCalculation calculation = new AttCalculation();

        String overtimeStr = calculation.calculateMonthlyOvertime(lEmpID);
        double totalOvertimeHours = convertToDecimalHours(overtimeStr);

        double totalWorkingDays = calculation.calculateInternSalary(lEmpID);
        int hours = (int) totalOvertimeHours;
        int minutes = (int) ((totalOvertimeHours - hours) * 60);

        System.out.println("\n----- Summary for User: " + lEmpID + " -----");
        System.out.println("Total Overtime: " + hours + " hours " + minutes + " minutes");
        System.out.println("Total Working Days: " + (int)totalWorkingDays);
        System.out.println("Total Late Days: " + totalLateDays);
        System.out.println("--------------------------------\n");
    }
    
    private void btnYerConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYerConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYerConActionPerformed

    private void btnYerEPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYerEPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYerEPFActionPerformed

    private void btnYerSoscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYerSoscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYerSoscoActionPerformed

    private void btnYerEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYerEISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYerEISActionPerformed

    private void btnYeeEPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeeEPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYeeEPFActionPerformed

    private void btnYeeSoscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeeSoscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYeeSoscoActionPerformed

    private void btnYeePCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeePCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYeePCBActionPerformed

    private void btnGSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGSalaryActionPerformed

    private void btnOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOTActionPerformed

    private void btnLatePenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatePenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLatePenActionPerformed

    private void btnAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllowanceActionPerformed

    private void btnYeeEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeeEISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYeeEISActionPerformed

    private void btnYeeNetSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeeNetSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYeeNetSalaryActionPerformed

    private void btnYeeTDeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeeTDeductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYeeTDeductionActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        lEmpID.setText("");
        lEmpName.setText("");
        lDep.setText("");
        lEmpType.setText("");
        lDOJ.setText("");
        btnYear.setText("");
        btnMonth.setSelectedIndex(0); 
        btnBasicSalary.setText("");
        btnAllowance.setText(""); 
        btnOT.setText("");
        btnLatePen.setText("");
        btnGSalary.setText("");
        btnYeeEPF.setText("");
        btnYeeSosco.setText("");
        btnYeeEIS.setText("");
        btnYeePCB.setText("");
        btnYeeTDeduction.setText("");
        btnYeeNetSalary.setText("");
        btnYerEPF.setText("");
        btnYerSosco.setText("");
        btnYerEIS.setText("");
        btnYerCon.setText("");
        lBankName.setText("");
        lBankAccount.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYearActionPerformed

    private String String(double totalOvertimeHours) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    class DataRowCounter {
        public static int countEmployees(String filePath) {
            int totalRows = 0;

            try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
                while (br.readLine() != null) {
                    totalRows++;
                }
            } catch (IOException e) {
                e.printStackTrace();
            }

            return totalRows;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Create().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BankAccount;
    private javax.swing.JLabel BankName;
    private javax.swing.JLabel BasicSalary;
    private javax.swing.JTabbedPane EmpTab;
    private javax.swing.JLabel GSalary;
    private javax.swing.JLabel OT;
    private javax.swing.JLabel Year;
    private javax.swing.JLabel YeeAmount;
    private javax.swing.JLabel YerAmount;
    private javax.swing.JLabel allowance;
    private javax.swing.JPanel box;
    private javax.swing.JPanel box1;
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JTextField btnAllowance;
    private javax.swing.JTextField btnBasicSalary;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnExit;
    private javax.swing.JTextField btnGSalary;
    private javax.swing.JTextField btnLatePen;
    private javax.swing.JComboBox<String> btnMonth;
    private javax.swing.JTextField btnOT;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnViewEmp;
    private javax.swing.JTextField btnYear;
    private javax.swing.JTextField btnYeeEIS;
    private javax.swing.JTextField btnYeeEPF;
    private javax.swing.JTextField btnYeeNetSalary;
    private javax.swing.JTextField btnYeePCB;
    private javax.swing.JTextField btnYeeSosco;
    private javax.swing.JTextField btnYeeTDeduction;
    private javax.swing.JTextField btnYerCon;
    private javax.swing.JTextField btnYerEIS;
    private javax.swing.JTextField btnYerEPF;
    private javax.swing.JTextField btnYerSosco;
    private javax.swing.JLabel dep;
    private javax.swing.JLabel dep1;
    private javax.swing.JLabel doj;
    private javax.swing.JLabel empID;
    private javax.swing.JLabel empName;
    private javax.swing.JPanel header;
    private javax.swing.JLabel header1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label lBankAccount;
    private java.awt.Label lBankName;
    private java.awt.Label lDOJ;
    private java.awt.Label lDep;
    private java.awt.Label lEmpID;
    private java.awt.Label lEmpName;
    private java.awt.Label lEmpType;
    private javax.swing.JLabel latePen;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JLabel month;
    private javax.swing.JLabel salaryDeduction;
    private javax.swing.JLabel salaryEarning;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel yeeEIS;
    private javax.swing.JLabel yeeEPF;
    private javax.swing.JLabel yeeNetSalary;
    private javax.swing.JLabel yeePCB;
    private javax.swing.JLabel yeeSosco;
    private javax.swing.JLabel yeeTDeduction;
    private javax.swing.JLabel yerCon;
    private javax.swing.JLabel yerEIS;
    private javax.swing.JLabel yerEPF;
    private javax.swing.JLabel yerSosco;
    // End of variables declaration//GEN-END:variables
}