package payrollManagement.payrollManager.Create;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hui Nan
 */

public class SearchUser extends javax.swing.JFrame {

    /**
     * Creates new form SearchUser
     */
    
    public SearchUser() {
        initComponents();
        loadTableData();

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
    }
    
    private void loadTableData() {
        String filePath = "usertxt.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            br.readLine();
            String[] columnsName = {"Employee ID", "Employee Name", "Department", "Employment Type", "Date of Joined", "Bank Name", "Bank Account"};
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setColumnIdentifiers(columnsName);
            
            String line;
            while ((line = br.readLine()) != null) {
                String[] dataRow = line.split(",");
                if (dataRow.length >= 7){
                    String[] selectedData = {dataRow[0], dataRow[1], dataRow[13], dataRow[15], dataRow[14], dataRow[20], dataRow[21]};
                    model.addRow(selectedData); 
                }
            }

        } catch (IOException ex) {
            Logger.getLogger(TextFileDataToJTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSearch = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setToolTipText("");
        mainPanel.setMinimumSize(new java.awt.Dimension(940, 600));
        mainPanel.setPreferredSize(new java.awt.Dimension(940, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 880, 260));

        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        mainPanel.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 250, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Search");
        mainPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        btnBack.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        mainPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, 30));

        headerPanel.setBackground(new java.awt.Color(128, 128, 128));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("EMPLOYEE DETAILS");
        header.setToolTipText("");
        headerPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 535, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        title.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        title.setForeground(new java.awt.Color(255, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("Table of Employee Details");
        mainPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollManagement/Images/Search.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 150));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee ID", "Employee Name", "Department", "Employment Type", "Date of Joined", "Bank Name", "Bank Account" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        mainPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchText = btnSearch.getText().trim().toLowerCase();
        String searchCriteria = (String) jComboBox1.getSelectedItem(); 
        String filePath = "usertxt.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            br.readLine();
            String[] columnsName = {"Employee ID", "Employee Name", "Department", "Employment Type", "Date of Joined", "Bank Name", "Bank Account"};
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            
            String line;
            while ((line = br.readLine()) != null) {
                String[] dataRow = line.split(",");
                if (dataRow.length >= 7){
                    String empID = dataRow[0].toLowerCase();
                    String empName = dataRow[1].toLowerCase();
                    String department = dataRow[13].toLowerCase(); 
                    String employmenttype = dataRow[15].toLowerCase();
                    String dateOfJoined = dataRow[14].toLowerCase();
                    String bankName = dataRow[20].toLowerCase();
                    String bankAccount = dataRow[21].toLowerCase();
                 
                    boolean match = false;

                    switch (searchCriteria) {
                        case "Employee ID":
                            match = empID.contains(searchText);
                            break;
                        case "Employee Name":
                            match = empName.contains(searchText);
                            break;
                        case "Department":
                            match = department.contains(searchText);
                            break; 
                        case "Employment Type":
                            match = employmenttype.contains(searchText);
                            break;
                        case "Date of Joined":
                            match = dateOfJoined.contains(searchText);
                            break;
                        case "Bank Name":
                            match = bankName.contains(searchText);
                            break;
                        case "Bank Account":
                            match = bankAccount.contains(searchText);
                            break;
                    }

                    if (match) {
                        String[] selectedData = {dataRow[0], dataRow[1], dataRow[13], dataRow[15], dataRow[14], dataRow[20], dataRow[21]};
                        model.addRow(selectedData); 
                    }
                }
            }

        } catch (IOException ex) {
            Logger.getLogger(SearchUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {                                     
        int selectedRow = table.getSelectedRow(); 

        String empID = table.getValueAt(selectedRow, 0).toString();
        String empName = table.getValueAt(selectedRow, 1).toString();
        String department = table.getValueAt(selectedRow, 2).toString();
        String employmenttype = table.getValueAt(selectedRow, 3).toString();
        String dateOfJoined = table.getValueAt(selectedRow, 4).toString();
        String bankName = table.getValueAt(selectedRow, 5).toString();
        String bankAccount = table.getValueAt(selectedRow, 6).toString();
        Create createForm = new Create();

        createForm.setButtonValues(empID, empName, department, employmenttype, dateOfJoined, bankName, bankAccount);

        createForm.setVisible(true);
        this.dispose();
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        payrollManagement.payrollManager.Create.Create create= new payrollManagement.payrollManager.Create.Create();
        create.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SearchUser().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField btnSearch;
    private javax.swing.JLabel header;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private static class TextFileDataToJTable {
        public TextFileDataToJTable() {
        }
    }
}