package payrollManagement.payrollManager.Payslip;

import java.awt.Color;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hui Nan
 */

public class Payslip extends javax.swing.JFrame {

    /**
     * Creates new form Payslip
     */
    
    public Payslip() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        YeeSosco = new javax.swing.JLabel();
        yeePCB = new javax.swing.JLabel();
        yeeEPF = new javax.swing.JLabel();
        yeeEIS = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Deductions = new javax.swing.JLabel();
        Amount1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        yeeTDeductions = new javax.swing.JLabel();
        jYeeTDeductions = new javax.swing.JLabel();
        jYeeSosco = new javax.swing.JLabel();
        jYeeEPF = new javax.swing.JLabel();
        jYeePCB = new javax.swing.JLabel();
        jYeeEIS = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        OT = new javax.swing.JLabel();
        latePen = new javax.swing.JLabel();
        allowance = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Earning = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        yeeGSalary = new javax.swing.JLabel();
        jGSalary = new javax.swing.JLabel();
        BSalary = new javax.swing.JLabel();
        jAllowance = new javax.swing.JLabel();
        jBSalary = new javax.swing.JLabel();
        jOT = new javax.swing.JLabel();
        jLatePen = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        yeeNetSalary = new javax.swing.JLabel();
        jYeeNSalary = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        yerEPF = new javax.swing.JLabel();
        yerSosco = new javax.swing.JLabel();
        yerEIS = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        EmpCon = new javax.swing.JLabel();
        Amount2 = new javax.swing.JLabel();
        jYerEPF = new javax.swing.JLabel();
        jYerSosco = new javax.swing.JLabel();
        jYerEIS = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        EmpCon1 = new javax.swing.JLabel();
        jYerCon = new javax.swing.JLabel();
        empID = new javax.swing.JLabel();
        empName = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        BankAccount = new javax.swing.JLabel();
        jEmpName = new javax.swing.JLabel();
        jEmpID = new javax.swing.JLabel();
        jBankAccount = new javax.swing.JLabel();
        jMonth = new javax.swing.JLabel();
        BankName = new javax.swing.JLabel();
        jBankName = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        jYear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setToolTipText("");
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(128, 128, 128));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("PAYSLIP");
        header.setToolTipText("");
        headerPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 535, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        btnExit.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        mainPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, -1, 30));

        btnDownload.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnDownload.setText("Save & Print");
        btnDownload.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        mainPanel.add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 110, 30));

        btnBack.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        mainPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        YeeSosco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        YeeSosco.setText("-Sosco");

        yeePCB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeePCB.setText("-PCB");

        yeeEPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeEPF.setText("-EPF");

        yeeEIS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeEIS.setText("-EIS");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        Deductions.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Deductions.setForeground(new java.awt.Color(255, 0, 0));
        Deductions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deductions.setText("Deductions");

        Amount1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Amount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Amount1.setText("Amount (RM)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Deductions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(Amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Amount1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Deductions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        yeeTDeductions.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeTDeductions.setForeground(new java.awt.Color(0, 51, 255));
        yeeTDeductions.setText("Total Deductions");

        jYeeTDeductions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(yeeTDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jYeeTDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeeTDeductions, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jYeeTDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yeeEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeeEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YeeSosco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeePCB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYeeEPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYeeSosco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYeeEIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYeePCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yeeEPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(YeeSosco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yeeEIS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yeePCB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jYeeEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jYeeSosco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jYeeEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jYeePCB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 410, 230));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        OT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OT.setText("+Over Time");

        latePen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        latePen.setText("- Late Penalty");

        allowance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allowance.setText("+Allowance");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        Earning.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Earning.setForeground(new java.awt.Color(255, 0, 0));
        Earning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Earning.setText("Earnings");

        Amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Amount.setText("Amount (RM)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Earning, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Earning)
                    .addComponent(Amount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        yeeGSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yeeGSalary.setForeground(new java.awt.Color(0, 51, 255));
        yeeGSalary.setText("Gross Salary  ");

        jGSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(yeeGSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jGSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeeGSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jGSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSalary.setText("Basic Salary");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allowance, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(latePen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAllowance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLatePen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSalary)
                    .addComponent(jBSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allowance)
                    .addComponent(jAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(OT)
                        .addGap(18, 18, 18)
                        .addComponent(latePen))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jOT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLatePen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 410, 230));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        yeeNetSalary.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        yeeNetSalary.setForeground(new java.awt.Color(255, 0, 0));
        yeeNetSalary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        yeeNetSalary.setText("Net Salary              ");

        jYeeNSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(yeeNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jYeeNSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yeeNetSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jYeeNSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 840, 30));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        yerEPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yerEPF.setText("EPF                            ");

        yerSosco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yerSosco.setText("Sosco                        ");

        yerEIS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yerEIS.setText("EIS                           ");

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        EmpCon.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        EmpCon.setForeground(new java.awt.Color(255, 0, 0));
        EmpCon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmpCon.setText("Employee Contribution");

        Amount2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Amount2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Amount2.setText("Amount (RM)");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(EmpCon, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Amount2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpCon)
                    .addComponent(Amount2))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, null));

        EmpCon1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        EmpCon1.setForeground(new java.awt.Color(255, 0, 0));
        EmpCon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmpCon1.setText("Total Contribution  ");

        jYerCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(EmpCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jYerCon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpCon1)
                    .addComponent(jYerCon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yerEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yerEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yerSosco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jYerEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(564, 564, 564)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jYerEIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jYerSosco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(yerEPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yerSosco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yerEIS))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jYerEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jYerSosco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYerEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 840, 160));

        empID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empID.setText("Employee ID             :");
        mainPanel.add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        empName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empName.setText("Employee Name       :");
        mainPanel.add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        month.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        month.setText("Month            :");
        mainPanel.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 110, -1));

        BankAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BankAccount.setText("Bank Account           :");
        mainPanel.add(BankAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));
        mainPanel.add(jEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 100, 20));
        mainPanel.add(jEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 100, 20));
        mainPanel.add(jBankAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 150, 20));
        mainPanel.add(jMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 100, 20));

        BankName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BankName.setText("Bank Name               :");
        mainPanel.add(BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));
        mainPanel.add(jBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 150, 20));

        Year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Year.setText("Year               :");
        mainPanel.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 110, -1));
        mainPanel.add(jYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    public void setLabelValues(String empID, String empName, String bankName, String bankAccount, String year, String month, String bSalary, 
                               String allowance,String ot, String latePen, String gSalary, String yeeEPF, String yeeSosco, String yeeEIS, 
                               String yeePCB,String yeeTDeductions, String yeeNSalary, String yerEPF, String yerSosco, String yerEIS, String yerCon) {
        jEmpID.setText(empID);
        jEmpName.setText(empName);
        jBankName.setText(bankName);
        jBankAccount.setText(bankAccount);
        jYear.setText(year);
        jMonth.setText(month);
        jBSalary.setText(bSalary);
        jAllowance.setText(allowance);
        jOT.setText(ot);
        jLatePen.setText(latePen);
        jGSalary.setText(gSalary);
        jYeeEPF.setText(yeeEPF);
        jYeeSosco.setText(yeeSosco);
        jYeeEIS.setText(yeeEIS);
        jYeePCB.setText(yeePCB);
        jYeeTDeductions.setText(yeeTDeductions);
        jYeeNSalary.setText(yeeNSalary);
        jYerEPF.setText(yerEPF);
        jYerSosco.setText(yerSosco);
        jYerEIS.setText(yerEIS);
        jYerCon.setText(yerCon);
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        payrollManagement.payrollManager.Payslip.SearchPayslip search= new payrollManagement.payrollManager.Payslip.SearchPayslip();
        search.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        Color originalMainPanelColor = mainPanel.getBackground();
        Color originalHeaderPanelColor = headerPanel.getBackground();
        Color originalPanel1Color = jPanel1.getBackground();
        Color originalPanel2Color = jPanel2.getBackground();
        Color originalPanel3Color = jPanel3.getBackground();
        Color originalPanel4Color = jPanel4.getBackground();
        Color originalPanel5Color = jPanel5.getBackground();
        Color originalPanel6Color = jPanel6.getBackground();
        Color originalPanel7Color = jPanel7.getBackground();
        Color originalPanel8Color = jPanel8.getBackground();
        Color originalPanel9Color = jPanel9.getBackground();
        Color originalPanel10Color = jPanel10.getBackground();

        btnDownload.setVisible(false);
        btnBack.setVisible(false);
        btnExit.setVisible(false);
        mainPanel.setBackground(Color.WHITE);
        headerPanel.setBackground(Color.WHITE);
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
        jPanel3.setBackground(Color.WHITE);
        jPanel4.setBackground(Color.WHITE);
        jPanel5.setBackground(Color.WHITE);
        jPanel6.setBackground(Color.WHITE);
        jPanel7.setBackground(Color.WHITE);
        jPanel8.setBackground(Color.WHITE);
        jPanel9.setBackground(Color.WHITE);
        jPanel10.setBackground(Color.WHITE);

        try {
            int scaleFactor = 2;
            BufferedImage bi = new BufferedImage(mainPanel.getWidth() * scaleFactor, mainPanel.getHeight() * scaleFactor, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = bi.createGraphics();
            g2d.scale(scaleFactor, scaleFactor);
            mainPanel.paint(g2d);
            g2d.dispose();

            String timestamp = new SimpleDateFormat("yyyy-MM-dd-hh-mm-ss").format(new Date());
            String imagePath = "HRMS_2\\src\\payrollManagement\\payslippayrollManager\\PayslipFiles\\png\\2024\\payslip_" + timestamp + ".png";
            ImageIO.write(bi, "png", new File(imagePath));

            Document document = new Document(PageSize.A4.rotate());
            String pdfPath = "HRMS_2\\src\\payrollManagement\\payrollManager\\PayslipFiles\\pdf\\2024\\payslip_" + timestamp + ".pdf";
            PdfWriter.getInstance(document, new FileOutputStream(pdfPath));
            document.open();

            float pdfWidth = PageSize.A4.rotate().getWidth();
            float pdfHeight = PageSize.A4.rotate().getHeight();

            Image image = Image.getInstance(imagePath);
            image.scaleToFit(pdfWidth, pdfHeight);
            image.setAlignment(Image.ALIGN_CENTER);
            document.add(image);

            document.close();

            JOptionPane.showMessageDialog(null, "Payslip saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        } finally {
            mainPanel.setBackground(originalMainPanelColor);
            headerPanel.setBackground(originalHeaderPanelColor);
            jPanel1.setBackground(originalPanel1Color);
            jPanel2.setBackground(originalPanel2Color);
            jPanel3.setBackground(originalPanel3Color);
            jPanel4.setBackground(originalPanel4Color);
            jPanel5.setBackground(originalPanel5Color);
            jPanel6.setBackground(originalPanel6Color);
            jPanel7.setBackground(originalPanel7Color);
            jPanel8.setBackground(originalPanel8Color);
            jPanel9.setBackground(originalPanel9Color);
            jPanel10.setBackground(originalPanel10Color);

            btnDownload.setVisible(true);
            btnBack.setVisible(true);
            btnExit.setVisible(true); 
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ui.dashboard.BackButton backButton = new ui.dashboard.BackButton();
        backButton.navigateBasedOnRole();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Payslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel Amount1;
    private javax.swing.JLabel Amount2;
    private javax.swing.JLabel BSalary;
    private javax.swing.JLabel BankAccount;
    private javax.swing.JLabel BankName;
    private javax.swing.JLabel Deductions;
    private javax.swing.JLabel Earning;
    private javax.swing.JLabel EmpCon;
    private javax.swing.JLabel EmpCon1;
    private javax.swing.JLabel OT;
    private javax.swing.JLabel Year;
    private javax.swing.JLabel YeeSosco;
    private javax.swing.JLabel allowance;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel empID;
    private javax.swing.JLabel empName;
    private javax.swing.JLabel header;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jAllowance;
    private javax.swing.JLabel jBSalary;
    private javax.swing.JLabel jBankAccount;
    private javax.swing.JLabel jBankName;
    private javax.swing.JLabel jEmpID;
    private javax.swing.JLabel jEmpName;
    private javax.swing.JLabel jGSalary;
    private javax.swing.JLabel jLatePen;
    private javax.swing.JLabel jMonth;
    private javax.swing.JLabel jOT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jYear;
    private javax.swing.JLabel jYeeEIS;
    private javax.swing.JLabel jYeeEPF;
    private javax.swing.JLabel jYeeNSalary;
    private javax.swing.JLabel jYeePCB;
    private javax.swing.JLabel jYeeSosco;
    private javax.swing.JLabel jYeeTDeductions;
    private javax.swing.JLabel jYerCon;
    private javax.swing.JLabel jYerEIS;
    private javax.swing.JLabel jYerEPF;
    private javax.swing.JLabel jYerSosco;
    private javax.swing.JLabel latePen;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel month;
    private javax.swing.JLabel yeeEIS;
    private javax.swing.JLabel yeeEPF;
    private javax.swing.JLabel yeeGSalary;
    private javax.swing.JLabel yeeNetSalary;
    private javax.swing.JLabel yeePCB;
    private javax.swing.JLabel yeeTDeductions;
    private javax.swing.JLabel yerEIS;
    private javax.swing.JLabel yerEPF;
    private javax.swing.JLabel yerSosco;
    // End of variables declaration//GEN-END:variables

    static class TextFileDataToJTable {

        public TextFileDataToJTable() {
        }
    }
}